[package]
name = "systems"
version = "0.1.0"
authors = [""]

[dependencies]
rand = "0.4"
regex = "0.2"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.9"


[lib]
name = "systems"
crate-type = ["rlib", "dylib"]
